version: '3.8'
services:
  api:
    container_name: ms-vecinet-post
    build: .
    ports:
      - "8093:8093"
    env_file:
      - .env
    volumes:
      - .:/app
      - gradle-cache:/home/gradle/.gradle
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge

volumes:
  gradle-cache:
  rabbitmq_data:
  rabbitmq_log: