spring:
  application:
    name: post

server:
  port: ${SERVER_PORT}

environment:
  mongo:
    username: ${MONGO_USERNAME}
    password: ${MONGO_PASSWORD}
    cluster: ${MONGO_CLUSTER}
    database: ${MONGO_DATABASE}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    create_post_queue: ${RABBITMQ_CREATE_POST_QUEUE}
    create_post_exchange: ${RABBITMQ_CREATE_POST_EXCHANGE}
    create_post_routing_key: ${RABBITMQ_CREATE_POST_ROUTING_KEY}

# Configuracion de Swagger Open Api
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    displayRequestDuration: true
  openapi:
    info:
      title: Vecinet API
      description: API documentation for Vecinet Authenticator
      version: v1.0.0
      contact:
        name: Vecinet Support
        url: http://vecinet.com/support
        email: support@vecinet.com